name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Navigate to /app and install dependencies
        run: |
          cd app
          npm install

      # - name: Run unit tests in /app
      #   run: |
      #     cd app
      #     npm test

      # - name: Run integration tests in /app
      #   run: |
      #     cd app
      #     npm run test:integration

  test-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Pulumi
        uses: pulumi/actions@v4
        with:
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Navigate to /infra and install dependencies
        run: |
          cd infra
          npm install

      - name: Validate Pulumi infrastructure
        run: |
          cd infra
          pulumi preview --stack dev
