# name: CI Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test-backend:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3 

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18 

#       - name: Navigate to /app and install dependencies   
#         run: |
#           cd app
#           npm install

#   test-infra:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
      
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
      
#       - name: Authenticate to Google Cloud
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
#       - name: Setup gcloud CLI
#         uses: google-github-actions/setup-gcloud@v2
#         with:
#           project_id: ${{ secrets.PROJECT_ID }}
      
#       - name: Verify Authentication
#         run: gcloud auth list
      
#       - name: Set up Pulumi
#         uses: pulumi/actions@v4
#         with:
#           pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      
#       - name: Configure Pulumi Backend (Google Cloud Storage)
#         run: |
#           echo "Setting up Pulumi backend storage in GCS..."
#           echo "PULUMI_BACKEND_URL=gs://shortlet-pulumi-state" >> $GITHUB_ENV
#           echo "PULUMI_CONFIG_PASSPHRASE=${{ secrets.PULUMI_CONFIG_PASSPHRASE }}" >> $GITHUB_ENV
      
#       - name: Install dependencies for infra
#         run: npm install
#         working-directory: infra
      
#       - name: Initialize or Select Pulumi Stack (Development)
#         run: |
#           pulumi stack select development --cwd infra || pulumi stack init development --cwd infra
#         env:
#           PULUMI_BACKEND_URL: gs://shortlet-pulumi-state
#           PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      
#       - name: Run Pulumi Preview for Development
#         uses: pulumi/actions@v6
#         with:
#           command: preview
#           stack-name: development
#           comment-on-pr: true
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           work-dir: infra
#           upsert: true
#         env:
#           PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
#           PULUMI_BACKEND_URL: gs://shortlet-pulumi-state
#           PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}





name: Deploy Infrastructure

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud auth list

      - name: Set Google Application Credentials
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Pulumi Login
        run: pulumi login gs://shortlet-pulumi-state

      - name: Set Pulumi Backend Environment Variables
        run: |
          echo "PULUMI_BACKEND_URL=gs://shortlet-pulumi-state" >> $GITHUB_ENV
          echo "PULUMI_CONFIG_PASSPHRASE=${{ secrets.PULUMI_CONFIG_PASSPHRASE }}" >> $GITHUB_ENV

      - name: List existing Pulumi stacks
        run: pulumi stack ls
        working-directory: infra

      - name: Initialize or Select Pulumi Stack
        run: |
          pulumi stack select development --cwd infra || pulumi stack init development --cwd infra
          pulumi stack ls --cwd infra  # Ensure the stack is recognized
        env:
          PULUMI_BACKEND_URL: gs://shortlet-pulumi-state
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

      - name: Wait for Pulumi Stack Recognition (Fix for CI Delay)
        run: sleep 5  # Gives time for Pulumi backend to recognize the new stack

      - name: Run Pulumi Preview
        run: |
         ls -l     
         cd infra
         ls -la
         pulumi stack select development --cwd infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        working-directory: infra


  # deploy:
  #   needs: test-preview
  #   if: github.ref == 'refs/heads/main'
  #   strategy:
  #     matrix:
  #       env: ['dev', 'staging', 'prod']
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: google-github-actions/setup-gcloud@v2
  #   - uses: actions/setup-node@v4
  #   - run: npm ci
  #   - run: pulumi login gs://your-state-bucket
  #   - run: pulumi up --stack ${{ matrix.env }} --yes --non-interactive
  #     env:
  #       PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}




















