name: Deploy Infrastructure

on:
  push:
    branches: [main]
  pull_request:


jobs:

  pulumi-up:
    name: pulumi-up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./infra
        run: npm install

      - name: Set up Google Cloud Credentials
        run: echo "${{ secrets.GCP_CREDENTIALS }}" > $HOME/gcp-credentials.json

      - name: Create the resources
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: organization/shortlet-infrastructure/development
          work-dir: ./infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gcp-credentials.json


